[build]
  base = "frontend"
  command = "npm install && ng build --configuration=production"
  publish = "dist/anushka-infosys/browser"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"